name = "TestTagBot"
uuid = "ade42d9a-f0a7-4d7c-9f72-e1874134871e"
authors = ["okatsn <okatsn@gmail.com> and contributors"]
version = "0.1.1-DEV"

[deps]
OkPkgTemplates = "38290ba8-8fbe-457b-bf75-0e4980da3840"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
