name: TestPkgDev
on:
  push:
    paths:
      - 'VersionTemp.toml'
      - '.github/workflows/PkgDev.yml'
  workflow_dispatch:


permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  TestPkgDev:
    runs-on: ubuntu-20.04
    steps: 
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.6.7
      - uses: actions/checkout@v3 # see https://github.com/actions/checkout
      - run: |
          git config user.email "action@github.com"
          git config user.name "github-actions"
          julia --project=@. -e '
            using Pkg;
            Pkg.Registry.add(RegistrySpec(url = "https://github.com/okatsn/OkRegistry.git"));
            Pkg.Registry.update();
            Pkg.instantiate();
            Pkg.dev("TestTagBot");
            using PkgDev;
            PkgDev.tag("TestTagBot", v"0.2.11"; github_username="github-actions", release_notes="Hello World");
            '