# Modified from the [Default TagBot template in PkgTemplates](https://github.com/JuliaCI/PkgTemplates.jl/blob/master/templates/github/workflows/TagBot.yml)
# Trigger TagBot only if
name: TagBot

on:
  repository_dispatch:
    types: [trigger-tagbot]
  issue_comment:
    types:
      - created
  workflow_dispatch:

## Allow permissions may fix some error; also see register.yml
## - see [Tagbot-setup](https://github.com/JuliaRegistries/TagBot#setup)
permissions:
  contents: write

jobs:
  TagBot:
    if: github.event_name == 'repository_dispatch' # if true, there is github.event.client_payload
    runs-on: ubuntu-latest
    steps:
      # - name: set env variables for changelog
      #   run: echo "COMMIT_MSG=''"
      # - name: Redefine variable under condition
      #   run: echo "COMMIT_MSG=${{github.event.client_payload.commit_msg}}"
      #   if: github.event_name == 'repository_dispatch'
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.DOCUMENTER_KEY }}
          changelog: |
            ## {{ package }} {{ version }}
            **Commit 0.2.26**
            ${{ github.event.client_payload.commit_msg }}
            {% if commits %}
            **Commits**
            {% for commit in commits %}
            - {{ commit.message }} (by {{ commit.author }})
            {% endfor %}
            {% endif %}
            {% if previous_release %}
            [Diff since {{ previous_release }}]({{ compare_url }})
            {% endif %}
            {% if custom %}
            {{ custom }}
            {% endif %}
            {% if issues %}
            **Closed issues:**
            {% for issue in issues %}
            - {{ issue.title }} (#{{ issue.number }})
            {% endfor %}
            {% endif %}
            {% if pulls %}
            **Merged pull requests:**
            {% for pull in pulls %}
            - {{ pull.title }} (#{{ pull.number }}) (@{{ pull.author.username }})
            {% endfor %}
            {% endif %}

          registry: okatsn/OkRegistry
